name: Documentation

on:
  push:
    branches: [main]
    paths:
      - mkdocs.yml
      - 'docs/**'
      - 'src/**'
  pull_request:
    paths:
      - mkdocs.yml
      - 'docs/**'
      - 'src/**'
  workflow_dispatch:

jobs:
  docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install the latest version of uv and set the python version to 3.11.11
        uses: astral-sh/setup-uv@v3
        with:
            python-version: 3.11.11

      - name: Configure git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create a virtual environment
        run: uv venv

      - name: Install dependencies with uv
        run: |
          source .venv/bin/activate
          uv sync --group docs

      - name: Build docs
        if: github.event_name == 'pull_request'
        run: |
          source .venv/bin/activate
          uv run mkdocs build -s

      - name: Publish docs
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        run: |
          source .venv/bin/activate
          uv run mkdocs gh-deploy
