name: Tests

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
  workflow_dispatch:

jobs:
  run-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv and set the python version to 3.11.11
        uses: astral-sh/setup-uv@v3
        with:
            python-version: 3.11.11

      - name: Create a virtual environment
        run: uv venv

      - name: Install dependencies with uv
        run: |
          source .venv/bin/activate
          uv sync

      - name: Install test dependencies
        run: |
          source .venv/bin/activate
          uv sync --group tests

      - name: Debug environment
        env:
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          source .venv/bin/activate
          export MISTRAL_API_KEY="${MISTRAL_API_KEY}"
          export OPENAI_API_KEY="${OPENAI_API_KEY}"
          if [ -n "$MISTRAL_API_KEY" ]; then
            echo "MISTRAL_API_KEY is set"
          else
            echo "MISTRAL_API_KEY is NOT set"
          fi
          if [ -n "$OPENAI_API_KEY" ]; then
            echo "OPENAI_API_KEY is set"
          else
            echo "OPENAI_API_KEY is NOT set"
          fi

      - name: Run tests
        env:
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          source .venv/bin/activate
          export MISTRAL_API_KEY="${MISTRAL_API_KEY}"
          export OPENAI_API_KEY="${OPENAI_API_KEY}"
          uv run pytest -v tests/
